name: "Build & Cache"

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover-matrix:
    runs-on: ubuntu-24.04

    outputs:
      matrix: ${{ steps.discover-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v21
      - id: discover-matrix
        run: |
          echo "matrix=$(nix eval --json .#ghaMatrix)" >> "$GITHUB_OUTPUT"

  build-and-push:
    needs: discover-matrix

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.discover-matrix.outputs.matrix) }}

    runs-on: ${{ matrix.gha-runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: jlumbroso/free-disk-space@v1.3.1

      - uses: DeterminateSystems/nix-installer-action@v21
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Build ${{ matrix.name }}
        run: |
          nix build .#${{ matrix.target }}

      - name: Push ${{ matrix.name }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.NIX_CACHE_SSH_PRIVKEY }}")
          nix copy --to "ssh://nix-cache@nix-cache.ldryt.dev" ./result
