name: "Build & Cache"

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover-matrix:
    runs-on: ubuntu-24.04

    outputs:
      matrix: ${{ steps.discover-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v21
      - id: discover-matrix
        run: |
          echo "matrix=$(nix eval --json .#ghaMatrix)" >> "$GITHUB_OUTPUT"

  build-and-push:
    needs: discover-matrix

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.discover-matrix.outputs.matrix) }}

    runs-on: >-
      ${{ 
        matrix.platform == 'aarch64-linux' && 'ubuntu-24.04-arm' || 
        matrix.platform == 'aarch64-darwin' && 'macos-15' || 
        matrix.platform == 'x86_64-darwin' && 'macos-15-intel' || 
        'ubuntu-24.04' 
      }}

    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        if: matrix.platform == 'aarch64-linux' || matrix.platform == 'x86_64-linux'

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Build ${{ matrix.target }}
        run: |
          nix build ${{ matrix.target }}

      - name: Push ${{ matrix.target }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          echo "${{ secrets.NIX_CACHE_SSH_PRIVKEY }}" | ssh-add -
          nix copy --to "ssh://nix-cache@nix-cache.ldryt.dev" ./result
