name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # runs monthly

jobs:
  update-flake-inputs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          token: ${{ secrets.GH_TOKEN_INFRA_NIX_FLAKE_UPDATE }}
          pr-assignees: ldryt
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated
